steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1/${PROJECT_ID}/my-artifact/test:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1/${PROJECT_ID}/my-artifact/test:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pyflaskapp'
      - '--image'
      - 'us-central1/${PROJECT_ID}/my-artifact/test:latest'
      - '--region'
      - 'us-central1'
      - '--allow-unathenticated'
options:
  logging: CLOUD_LOGGING_ONLY